apiVersion: v1
kind: Service
metadata:
  name: implementer-interface
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    app: implementer-interface
    environment: dev
  type: NodePort
